export const VIRTUALIZE_CONSTANTS = {
    SKIP_ITEM_HEIGHT: 72,
    SKIP_PLACEHOLDER_PADDING_LEFT: 72,
    SKIP_PLACEHOLDER_PADDING_TOP: 14,
    DUPLICATE_PLACEHOLDER_PADDING_LEFT: 58,
    DUPLICATE_PLACEHOLDER_PADDING_TOP: 14,
};
