import { Action } from "redux";
import { ThunkAction } from "redux-thunk";
import { TState } from "./reducers";

export enum Actions {
    SETTINGS_SET_LANGUAGE = "SET_LANGUAGE",
    SETTINGS_SET_STUDIO_PATH = "SETTINGS_SET_STUDIO_PATH",

    NOTIFICATION_SET_TYPE = "NOTIFICATION_SET_TYPE",
    NOTIFICATION_SET_MESSAGE = "NOTIFICATION_SET_MESSAGE",
    NOTIFICATION_SET_VISIBLE = "NOTIFICATION_SET_VISIBLE",

    BACKDROP_SET_VISIBLE = "BACKDROP_SET_VISIBLE",

    CONFLICT_RESOLVER_SEARCH_SET_SEARCH_IN_PROGRESS = "CONFLICT_RESOLVER_SEARCH_SET_SEARCH_IN_PROGRESS",
    CONFLICT_RESOLVER_SEARCH_SET_RESULT = "CONFLICT_RESOLVER_SEARCH_SET_RESULT",
    CONFLICT_RESOLVER_SEARCH_SET_PROGRESS_RELATIVE = "CONFLICT_RESOLVER_SEARCH_SET_PROGRESS_RELATIVE",
    CONFLICT_RESOLVER_SELECT_FILES = "CONFLICT_RESOLVER_SELECT_FILES",
    CONFLICT_RESOLVER_SET_FILES_FILTER = "CONFLICT_RESOLVER_SET_FILES_FILTER",
    CONFLICT_RESOLVER_SET_SEARCH_DIRECTORY = "CONFLICT_RESOLVER_SET_SEARCH_DIRECTORY",
}

export interface ReduxAction {
    type: Actions;
}

export type ReduxThunkAction<TReturn = void> = ThunkAction<TReturn, TState, unknown, Action<Actions>>;
