export enum Actions {
    SET_LANGUAGE = "SET_LANGUAGE",
    NOTIFICATION_SET_TYPE = "NOTIFICATION_SET_TYPE",
    NOTIFICATION_SET_MESSAGE = "NOTIFICATION_SET_MESSAGE",
    NOTIFICATION_SET_VISIBLE = "NOTIFICATION_SET_VISIBLE",
    BACKDROP_SET_VISIBLE = "BACKDROP_SET_VISIBLE",
}

export interface ReduxAction {
    type: Actions;
}
